Repository FRONTENDSCHOOL5/final-25-would-you, pull requests merged in 2023-08, with the labels that each got.

#241 [feat]쉼표 기능 추가 #215
  src/api/productAPI.js
  src/pages/Product/ProductModi.jsx
Labels: feat

#243 [🎨 style] ProductModi css 변경 #242
  src/pages/Product/ProductModi.module.css
Labels: style

#244 [🐛 fix]ProductModi 오류 수정
  src/pages/Product/ProductModi.jsx
Labels: bug

#245 [✨] follow페이지 취소, 팔로우 기능 구현/#206
  src/pages/Follow/Followers/Followers.jsx
Labels: feat

#247 [♻️ refactor] 컨벤션 적용 코드 #246
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginMain/LoginMain.jsx
  src/pages/Product/AddProduct.jsx
  src/pages/Product/ProductModi.jsx
Labels: refactor

#248 [♻️ refacto] 채팅리스트 맞팔기준으로 리스트업하도록 수정 / #220
  src/pages/Chat/ChatList/ChatList.jsx
Labels: refactor

#249 [♻️ refactor] Feat/chat/chat list/ 페이지 필요없는 주석 및 변수 삭제 #220
  src/components/common/Chat/ChatItem.jsx
Labels: refactor

#253 [✨ feat] Upload페이지의 이미지 API 연동 및 분리 #233
  src/api/imagesAPI.js
  src/pages/Upload/Upload.jsx
Labels: feat

#255 [✨feat] 채팅방 나가기 기능 구현#207
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/AlertModal/AlertModal.module.css
  src/components/common/Modal/Modal.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.module.css
Labels: feat

#257 [fix] 게시글 마지막 이미지 볼 때, 왼쪽에 두번째 이미지가 잘려보이는 이슈 수정
  src/components/common/Post/Post.module.css
Labels: fix

#259 [fix] 앨범형으로 보기 클릭 시, 첫번째 이미지가 보이도록 수정 #258
  src/components/common/Profile/ProfilePost.jsx
Labels: fix

#260 [♻️ refactor] join 페이지 리팩토링#196
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinEmail/JoinEmail.module.css
Labels: refactor

#262 [🐛 fix] ProductModi 버튼 활성화 수정 #261
  src/pages/Product/ProductModi.jsx
  src/pages/Product/ProductModi.module.css
Labels: bug

#263 [✨ feat] Upload페이지의 이미지 API 연동 및 분리 #233
  src/pages/Upload/Upload.jsx
Labels: feat

#265 [fix] 로그아웃 후 다른 계정으로 로그인 시, 프로필 페이지에서 이전 계정의 유저 정보가 보이는 이슈
  src/api/profileAPI.js
  src/components/common/Profile/UserProfile.jsx
  src/pages/Profile/MyProfile/MyProfile.jsx
Labels: fix

#267 [design] 게시글 내 컨텐츠 유무에 따른 margin 조정 #266
  src/components/common/Post/Post.jsx
Labels: design

#269 [fix] 프로필 페이지 split 에러 #268
  src/components/common/Post/Post.jsx
Labels: fix

#274 [🐛 fix] Productmodi button type 변경 #273
  src/components/common/Header/Header.jsx
Labels: bug

#275 [fix] 회원가입프로필설정 페이지 레이아웃 중앙정렬로 맞춤 #196
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.module.css
Labels: fix

#282 [fix] 팔로잉 언팔 해당계정만 삭제하도록 수정 #280
  src/pages/Follow/Followings/Followings.jsx
Labels: fix

#284 [📝 docs] 1차 리팩토링 기준 기능구현 영상 및 팀소개 리드미 부분 수정 #165
  README.md
Labels: docs
