Repository FRONTENDSCHOOL5/final-25-would-you, pull requests merged in 2023-07, with the labels that each got.

#179 [feat] 검색 기능 추가 #178
  package-lock.json
  package.json
  src/components/common/HeaderTest/Header.jsx
  src/components/common/HeaderTest/Header.module.css
  src/components/common/Post/Post.jsx
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/User/User.module.css
  src/components/common/User/UserFollow/UserFollow.jsx
  src/components/common/User/UserSearch/UserSearch.jsx
  src/components/common/User/UserSearch/UserSearch.module.css
  src/components/layout/Layout.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/SearchUser.module.css
Labels: feat

#181 [chore] 안쓰는 파일 삭제 및 컴포넌트 명에 맞는 폴더 생성 후 이동 #180
  src/App.js
  src/components/common/Header/ChatHeader.jsx
  src/components/common/Header/FollowersHeader.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/HomeSearch.jsx
  src/components/common/Header/SaveButton.jsx
  src/components/common/Header/UploadButton.jsx
  src/components/common/Header/UserSearch.jsx
  src/components/common/HeaderTest/Header.jsx
  src/components/common/HeaderTest/Header.module.css
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/AlertModal/AlertModal.module.css
  src/components/common/Modal/IconProductModal.jsx
  src/components/common/Modal/IconProductModal.module.css
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModal.module.css
  src/components/common/Profile/ProfileAlbum.jsx
  src/components/common/Profile/ProfileAlbum.module.css
  src/components/layout/Layout.jsx
  src/hooks/dummy.txt
  src/pages/Follow/Follow.module.css
  src/pages/Follow/Followers/Followers.jsx
  src/pages/Follow/Followings/Followings.jsx
  src/pages/Profile/ProductList.jsx
  src/pages/Profile/ProductList.module.css
  src/pages/Profile/YourProfile/YourProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.module.css
  src/routes/dummy.txt
Labels: move, chore, remove

#185 [feat] 공구 중인 상품에 모달 연결, 검색 페이지 코드 수정 및 기능 개선 #182 #184
  src/App.js
  src/api/searchAPI.js
  src/components/common/Header/Header.jsx
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/Product/Product.jsx
  src/components/common/Profile/ProfileProduct.jsx
  src/components/common/User/UserSearch/UserSearch.jsx
  src/components/common/User/UserSearch/UserSearch.module.css
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Search/Search.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/SearchUser.module.css
Labels: feat, refactor

#188 프로필 페이지 API 코드 분리 및 리팩토링 #187
  src/api/postAPI.js
  src/api/productAPI.js
  src/api/profileAPI.js
  src/components/common/Profile/OtherProfile.jsx
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/Profile/ProfileProduct.jsx
Labels: refactor

#192 [fix] 프로필 페이지에서 팔로우 버튼 클릭할 때마다, 전체 UI가 렌더링 되는 이슈 수정 #191
  src/components/common/Profile/OtherProfile.jsx
Labels: fix

#194 [feat] YourProfile 페이지에서 사용자 정보 하단에 위치한 버튼 기능 추가 #193
  package-lock.json
  package.json
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/AlertModal/AlertModal.module.css
  src/components/common/Profile/OtherProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.jsx
Labels: feat

#197 [feat] 상세페이지에서 댓글 입력 기능 추가, 기존 API 코드 리팩토링, 댓글 관련 UI 수정
  src/api/commentAPI.js
  src/components/common/Comment/Comment.module.css
  src/components/common/Input/Input.jsx
  src/components/common/Input/Input.module.css
  src/components/layout/Layout.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Post/PostDetail.module.css
Labels: feat, design, refactor

#199 [feat] 댓글 삭제, 신고 기능 추가
  src/api/commentAPI.js
  src/api/profileAPI.js
  src/components/common/Comment/Comment.jsx
  src/components/common/Comment/Comment.module.css
  src/components/common/Input/Input.jsx
  src/components/common/Input/Input.module.css
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/Modal.jsx
  src/pages/Post/PostDetail.jsx
Labels: feat

#200 [✨ feat] 게시물 업로드 아이템들 수정 #183
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/Modal.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: feat

#201 Feat/api/#186
  README.md
  src/api/productAPI.js
  src/pages/Product/AddProduct.jsx
Labels: feat

#203 Feat/alert modal/#202
  src/components/common/Modal/AlertModal/AlertModal.jsx
Labels: style

#204 [✨ feat] 게시물 업로드 아이템들 수정 #183
  src/components/common/Modal/AlertModal/AlertModal.jsx
  src/components/common/Modal/AlertModal/AlertModal.module.css
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: feat, fix

#209 [fix] YourProfile 페이지에서 공유버튼 클릭 시, 전체 url 복사 되도록 수정 #208
  src/components/common/Profile/OtherProfile.jsx
Labels: fix

#211 [feat] 게시글 신고하기 기능 추가(API) #210
  src/api/postAPI.js
  src/components/common/Modal/Modal.jsx
Labels: feat

#216 [✨ feat] ProductModi 수정기능 추가 #215
  src/App.js
  src/api/productAPI.js
  src/components/common/Modal/Modal.jsx
  src/components/common/Product/Product.jsx
  src/components/layout/Layout.jsx
  src/pages/Product/ProductModi.jsx
  src/pages/Product/ProductModi.module.css
Labels: feat

#218 Feat/login api/#217
  src/pages/Login/LoginEmail/LoginEmail.jsx
Labels: feat

#219 [✨feat] 데이터 넘기기 오류 수정, 위치API연결 #205
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: feat, fix

#221 [✨feat] 채팅리스트 리팩토링(api연동 및 마크업수정)
  src/components/common/Chat/ChatItem.jsx
  src/components/common/Chat/ChatItem.module.css
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatList/ChatList.module.css
Labels: refactor

#225 [♻️ refactor] 프로필 수정페이지 주석 및 컨벤션 고침 #223
  src/pages/ProfileModification/ProfileModification.jsx
Labels: refactor

#226 [fix] 계정 ID 중복검사 오류 수정(현재 userIId 도 중복검사 오류로 뜨는거 수정) #223
  src/pages/ProfileModification/ProfileModification.jsx
Labels: refactor

#227 [fix] 게시글에서 일정 중 일시가 렌더링 될 때 날짜를 계산하도록 수정 #214
  src/components/common/Post/Post.jsx
Labels: fix

#229 [feat] follow페이지 리팩토링 #206
  src/api/followAPI.js
  src/pages/Follow/Follow.module.css
  src/pages/Follow/Followers/Followers.jsx
  src/pages/Follow/Followings/Followings.jsx
Labels: refactor

#230 [♻️ refactor]회원가입페이지 리팩토링#196
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.module.css
Labels: refactor

#232 [feat] 게시글 이미지가 2개 이상일 때 여러장의 이미지가 보여질 수 있도록 코드 추가 #228
  src/components/common/Post/Post.jsx
  src/components/common/Post/Post.module.css
  src/components/common/Profile/ProfilePost.jsx
Labels: feat

#235 [fix] 공구 중인 상품이 없을 때는, 영역 안보이게 처리 #234
  src/components/common/Profile/ProfileProduct.jsx
Labels: fix

#237 [fix] 피드 스크롤이 하단으로 가면 다시 최상단으로 올라가는 이슈 수정 #236
  src/components/common/Profile/ProfilePost.jsx
Labels: fix

#239 [design] 공구 중인 상품의 이름이 길어지면 말줄임 스타일 추가 #238
  src/components/common/Product/Product.module.css
Labels: design

#240 [♻️refactor] Upload페이지 api 분리 #231
  src/api/mapAPI.js
  src/api/uploadAPI.js
  src/pages/Upload/Upload.jsx
Labels: refactor
