Repository FRONTENDSCHOOL5/final-25-would-you, pull requests merged in 2023-06, with the labels that each got.

#2 [assets] 이미지 파일 추가 및 더미 파일 삭제 #1
  src/assets/dummy.txt
  src/assets/images/404.png
  src/assets/images/basic-profile-img.png
  src/assets/images/basic-profile-img36.png
  src/assets/images/facebook.png
  src/assets/images/full-logo.png
  src/assets/images/google.png
  src/assets/images/iccon-img-layers.svg
  src/assets/images/icon- more-vertical.svg
  src/assets/images/icon-arrow-left.svg
  src/assets/images/icon-calendar-16.svg
  src/assets/images/icon-calendar-24.svg
  src/assets/images/icon-edit.svg
  src/assets/images/icon-heart.svg
  src/assets/images/icon-home-fill.svg
  src/assets/images/icon-home.svg
  src/assets/images/icon-image.svg
  src/assets/images/icon-message-circle-1.svg
  src/assets/images/icon-message-circle-fill.svg
  src/assets/images/icon-message-circle.svg
  src/assets/images/icon-post-album-off.svg
  src/assets/images/icon-post-album-on.svg
  src/assets/images/icon-post-list-off.svg
  src/assets/images/icon-post-list-on.svg
  src/assets/images/icon-search.svg
  src/assets/images/icon-share.svg
  src/assets/images/icon-user-fill-16.svg
  src/assets/images/icon-user-fill-24.svg
  src/assets/images/icon-user-fill.svg
  src/assets/images/icon-user.svg
  src/assets/images/img-button-grey.png
  src/assets/images/img-button.png
  src/assets/images/map-16.svg
  src/assets/images/map-24.svg
  src/assets/images/menu-icon-16.svg
  src/assets/images/menu-icon-24.svg
  src/assets/images/message-circle.png
  src/assets/images/minus-active.svg
  src/assets/images/minus.svg
  src/assets/images/plus-active.svg
  src/assets/images/plus.svg
  src/assets/images/profile-img42.png
  src/assets/images/s-icon-more-vertical.svg
  src/assets/images/symbol-logo-grey.png
  src/assets/images/symbol-logo.png
  src/assets/images/upload-file.png
  src/assets/images/x.svg
Labels: assets

#4 [add] src 내 폴더 및 파일 생성 #3
  src/context/AuthContext.jsx
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Feed/Feed.jsx
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinEmail/JoinEmail.module.css
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginMain/LoginMain.jsx
  src/pages/Post/Post.jsx
  src/pages/Product/AddProduct.jsx
  src/pages/Profile/Profile.jsx
  src/pages/ProfileModification/ProfileModification.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Upload/Upload.jsx
Labels: add

#12 💄 [design] 공통 요소 중 삭제 모달, 하단 nav, 댓글 입력 컴포넌트 마크업 및 디자인 #11
  src/components/common/Input/InputComment.jsx
  src/components/common/Input/input.css
  src/components/common/Modal/AlertModal.jsx
  src/components/common/Modal/AlertModal.module.css
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/TabMenu/TabMenu.module.css
  src/styles/global.css
  src/styles/reset.css
Labels: design

#20 [💄design] 공통 요소 중 포스트 모달, 상품 모달 마크업 및 디자인#15
  src/components/common/Modal/IconProductModal.jsx
  src/components/common/Modal/IconProductModal.module.css
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModal.module.css
Labels: design

#22 [design] 이메일 회원가입 기능 추가 #17
  src/pages/Login/LoginMain/LoginMain.jsx
  src/pages/Login/LoginMain/LoginMain.module.css
Labels: design

#24 [design] LoginEmail Page 마크업 추가 했습니다! #23
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmail.module.css
Labels: design

#27 [design] Splash UI 작업 #18
  src/pages/Splash/Splash.jsx
  src/pages/Splash/Splash.module.css
Labels: design

#28 [design] 피드 페이지 마크업 #19
  src/assets/images/icon-heart-fill.svg
  src/pages/Feed/Feed.jsx
  src/pages/Feed/Feed.module.css
  src/pages/Feed/FeedNone.jsx
  src/pages/Feed/FeedNone.module.css
Labels: design

#30 [💄design] 팔로워페이지 마크업 #21
  src/pages/Profile/Followers.jsx
  src/pages/Profile/Followers.module.css
Labels: design

#32 [design] feat/add product 마크업 추가 /#25
  src/pages/Product/AddProduct.jsx
  src/pages/Product/AddProduct.module.css
Labels: design

#36 [💄(css) design] join page 마크업 추가 #31
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinEmail/JoinEmail.module.css
Labels: design

#38 [design] post 페이지 마크업 #29
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
Labels: design

#39 [design] Feat/search- page 마크업 추가/#33
  src/components/Common/User/User.module.css
  src/components/Common/User/UserFollow/UserFollow.jsx
  src/components/Common/User/UserSearch/UserSearch.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/SearchUser.module.css
Labels: design

#45 [🎨style] 팔로워페이지 class 수정 #44
  src/pages/Profile/Followers.jsx
Labels: style

#52 [💄design] upload페이지 마크업 #26
  src/assets/images/upload-text.png
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: design

#53 [feat] 코드 라우팅 기능 추가
  src/App.js
Labels: feat

#55 [design] MyProfile 마크업
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Profile/MyProfile/MyProfile.module.css
Labels: design

#56 [💄design] chat room 마크업#54
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.module.css
Labels: design

#58 [feat] props에 맞는 UI 리턴하는 코드 추가 #57
  src/components/Common/Input/Input.jsx
  src/components/Common/Input/Input.module.css
  src/components/common/Input/InputComment.jsx
Labels: feat

#59 [remove] 공통 컴포넌트 input.css 삭제 #57
  src/components/common/Input/input.css
Labels: remove

#60 [design] Your Profile 마크업 추가 #41
  src/pages/Profile/ProductList.jsx
  src/pages/Profile/ProductList.module.css
  src/pages/Profile/YourProfile.jsx
  src/pages/Profile/YourProfile.module.css
Labels: design

#64 [design] 레이아웃 컴포넌트 추가 및 레이아웃 컴포넌트에 맞춰 TabMenu 컴포넌트, Feed, MyProfile 페이지 수정
  src/assets/images/icon-edit-fill.svg
  src/components/Common/HeaderTest/Header.jsx
  src/components/Common/HeaderTest/Header.module.css
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/TabMenu/TabMenu.module.css
  src/components/dummy.txt
  src/components/layout/Layout.jsx
  src/components/layout/Layout.module.css
  src/pages/Feed/Feed.jsx
  src/pages/Feed/Feed.module.css
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Profile/MyProfile/MyProfile.module.css
  src/pages/Profile/Profile.jsx
Labels: design, refactor

#65 [refactor] Feed, MyProfile 페이지 컴포넌트로 분리
  src/components/Common/Post/Post.jsx
  src/components/Common/Post/Post.module.css
  src/components/Common/Product/Product.jsx
  src/components/Common/Product/Product.module.css
  src/components/Common/Profile/ProfilePost.jsx
  src/components/Common/Profile/ProfilePost.module.css
  src/components/Common/Profile/UserProfile.jsx
  src/components/Common/Profile/UserProfile.module.css
  src/components/common/Profile/ProfileProduct.jsx
  src/components/common/Profile/ProfileProduct.module.css
Labels: refactor

#69 [refactor] Post 페이지 컴포넌트 분리
  src/components/Common/Comment/Comment.jsx
  src/components/Common/Comment/Comment.module.css
  src/components/Common/HeaderTest/Header.jsx
  src/components/Common/Input/Input.jsx
  src/components/Common/Profile/ProfilePost.jsx
  src/components/Common/Profile/ProfilePost.module.css
  src/components/layout/Layout.jsx
  src/pages/Post/Post.jsx
  src/pages/Post/Post.module.css
  src/pages/Post/PostDetail.jsx
  src/pages/Post/PostDetail.module.css
Labels: refactor

#71 [feat] 라우터 추가(2차) , 레이아웃 컴포넌트 props 수정
  src/App.js
  src/components/Common/HeaderTest/Header.jsx
  src/components/Common/Post/Post.module.css
  src/components/Common/Profile/ProfilePost.module.css
  src/components/common/Profile/ProfileProduct.module.css
  src/components/common/TabMenu/TabMenu.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Layout.module.css
Labels: feat, design, refactor

#74 [🎨 style] 채팅리스트페이지 레이아웃 폼에 맞춰 수정
  src/components/layout/Layout.jsx
  src/pages/Chat/ChatList/ChatList.jsx
  src/pages/Chat/ChatList/ChatList.module.css
Labels: design

#75 [🎨style] Modal과 Page 코드 수정
  src/components/common/Modal/IconProductModal.jsx
  src/components/common/Modal/IconProductModal.module.css
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModal.module.css
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.module.css
  src/pages/Profile/Followers.jsx
  src/pages/Profile/Followers.module.css
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: style

#76 [style] LoginPage,Email,Search,Addproduct,Yourprofile 마크업 수정 #61
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmail.module.css
  src/pages/Login/LoginMain/LoginMain.jsx
  src/pages/Login/LoginMain/LoginMain.module.css
  src/pages/Product/AddProduct.jsx
  src/pages/Product/AddProduct.module.css
  src/pages/Profile/YourProfile.jsx
  src/pages/SearchUser/SearchUser.jsx
  src/pages/SearchUser/SearchUser.module.css
Labels: style

#80 [style] Post 관련 컴포넌트 padding, width 수정 #67
  src/components/common/Profile/ProfilePost.module.css
  src/pages/Post/PostDetail.module.css
Labels: design

#82 [style] Post 컴포넌트 padding 수정 #67
  src/components/common/Profile/ProfilePost.module.css
Labels: style

#89 [💄design] 레이아웃 Followers,Upload,ChatRoom 재수정 #85
  src/components/common/HeaderTest/Header.jsx
  src/components/common/Input/Input.jsx
  src/components/layout/Layout.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/ChatRoom.module.css
  src/pages/Upload/Upload.jsx
Labels: design

#90 [🎨 style] 프로필 수정페이지 레이아웃 적용 #47
  src/components/layout/Layout.jsx
  src/pages/ProfileModification/ProfileModification.jsx
  src/pages/ProfileModification/ProfileModification.module.css
Labels: design

#93 [style] Header 코드 추가 #61
  src/components/common/HeaderTest/Header.module.css
Labels: style

#94 [refator] 라우터 수정, LoginMain에서 LoginEmail 조건부 렌더링 로직 추가 #92
  src/App.js
  src/pages/Login/LoginMain/LoginMain.jsx
  src/pages/Login/LoginMain/LoginMain.module.css
Labels: refactor

#96 [🎨 style]input 위아래 패딩 추가 및 오타 수정 #47
  src/pages/ProfileModification/ProfileModification.jsx
  src/pages/ProfileModification/ProfileModification.module.css
Labels: design

#98 [🎨 style] input 패딩 추가 및 '소개입력 ⇒ 소개'로 오타 수정 # 37
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
Labels: design

#99 [🎨 style] input 패딩 추가 및 에러메시지 왼쪽 정렬 #31
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinEmail/JoinEmail.module.css
Labels: design

#101 [feat] 프로필 페이지에서 리스트 또는 앨범으로 보기 버튼에 기능 추가, 공통 컴포넌트 ProfilePost.jsx 간격 수정 #97
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/Profile/ProfilePost.module.css
  src/pages/Feed/Feed.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Profile/MyProfile/MyProfile.jsx
Labels: style, refactor

#104 [design] 공통 컴포넌트 레이아웃(헤더, 푸터) 수정 #102
  src/components/common/Comment/Comment.jsx
  src/components/common/Comment/Comment.module.css
  src/components/common/HeaderTest/Header.jsx
  src/components/common/HeaderTest/Header.module.css
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/TabMenu/TabMenu.module.css
  src/components/layout/Layout.jsx
Labels: design, refactor

#109 [feat] login 기능구현 #108
  src/components/layout/Layout.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmail.module.css
Labels: feat

#110 [✨feat] 회원가입 페이지 api연동 및 기능 구현 #100
  src/api/userAPI.js
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/utils/baseUrl.js
Labels: feat

#113 [🎨 style] chatItem 제목 폰트 굵기 500으로 변경 #50
  src/components/common/Chat/ChatItem.module.css
Labels: design

#115 [feat] product 페이지 기능 구현
  src/components/common/HeaderTest/Header.jsx
  src/pages/Product/AddProduct.jsx
  src/pages/Product/AddProduct.module.css
Labels: feat

#119 [feat] product 페이지 기능구현 #114
  src/components/common/HeaderTest/Header.jsx
  src/components/layout/Layout.jsx
  src/pages/Product/AddProduct.jsx
  src/pages/Product/AddProduct.module.css
Labels: feat

#120 [✨ feat] 회원가입 프로필 설정 페이지 api 연동 완료 #111
  src/api/imageAPI.js
  src/api/userAPI.js
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
Labels: feat

#122 [style] AddProduct 페이지 코드 수정#114
  src/pages/Product/AddProduct.jsx
Labels: style

#123 [feat] 게시글 상세 페이지 API 연결, 라우터 수정 #117
  src/App.js
  src/api/commentAPI.js
  src/api/postAPI.js
  src/api/productAPI.js
  src/api/profileAPI.js
  src/components/common/Comment/Comment.jsx
  src/components/common/HeaderTest/Header.jsx
  src/components/common/Post/Post.jsx
  src/components/common/Post/Post.module.css
  src/components/common/Product/Product.jsx
  src/components/common/Product/Product.module.css
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/Profile/ProfileProduct.jsx
  src/components/common/Profile/UserProfile.jsx
  src/components/common/Profile/UserProfile.module.css
  src/components/layout/Layout.jsx
  src/pages/Post/PostDetail.jsx
Labels: feat, fix, refactor

#126 [feat] 로컬스토리지에서 저장된 토큰 가져오도록 코드 추가 및 Splash 화면 연결 #124
  src/components/common/HeaderTest/Header.jsx
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/Profile/ProfileProduct.jsx
  src/components/common/Profile/UserProfile.jsx
  src/pages/Feed/Feed.jsx
  src/pages/Post/PostDetail.jsx
  src/pages/Splash/Splash.module.css
Labels: feat

#129 [feat] chat 마크업 및 기능추가 #128
  src/components/common/Chat/ChatItem.jsx
  src/components/common/Chat/ChatItem.module.css
  src/pages/Chat/ChatList/ChatList.module.css
Labels: feat

#130 [✨feat]Followers API 연동 및 버튼 구현
  src/pages/Profile/Followers.jsx
  src/pages/Profile/Followers.module.css
Labels: feat

#131 [feat] 로그인 유무에 따라 페이지가 렌더링 되는 기능 추가 #127
  src/pages/Feed/Feed.jsx
  src/pages/Feed/FeedNone.jsx
  src/pages/Feed/FeedNone.module.css
  src/pages/Splash/Splash.module.css
Labels: feat

#133 [feat] 좋아요 기능 구현 #132
  src/components/common/Post/Post.jsx
Labels: feat

#135 [feat] 유저 프로필 API 연결 #134
  src/components/common/Profile/OtherProfile.jsx
  src/components/common/Profile/OtherProfile.module.css
  src/components/common/Profile/ProfilePost.jsx
  src/components/common/Profile/ProfileProduct.jsx
  src/components/common/Profile/ProfileProduct.module.css
  src/pages/Profile/YourProfile.jsx
Labels: feat

#136 [feat] 유저 프로필 팔로우 기능 추가 #134
  src/components/common/HeaderTest/Header.jsx
  src/components/common/Profile/OtherProfile.jsx
  src/components/common/Profile/OtherProfile.module.css
  src/components/layout/Layout.jsx
Labels: feat

#137 [style] AddProduct 기능 수정 #114
  src/pages/Product/AddProduct.jsx
Labels: style

#138 [✨ feat] 프로필 수정페이지 api 연동해서 수정 기능 구현 #121
  src/api/profileAPI2.js
  src/components/layout/Layout.jsx
  src/context/AuthContext.jsx
  src/index.js
  src/pages/ProfileModification/ProfileModification.jsx
  src/pages/ProfileModification/ProfileModification.module.css
Labels: feat

#139 [feat] 팔로잉 리스트 api 연동 완료 및 기능구현 완료 #105
  src/api/followAPI.js
  src/pages/Profile/Followers.jsx
  src/pages/Profile/Followers.module.css
  src/pages/Profile/MyProfile/Followings.jsx
Labels: feat

#140 [style] AddProduct 코드 수정
  src/pages/Product/AddProduct.jsx
Labels: style

#141 [fix] 팔로우 버튼 동시 변경되는 버그 수정 #105
  src/pages/Profile/Followers.jsx
Labels: fix

#144 [feat] 팔로잉 페이지 라우터 추가 및 프로필에서 팔로잉 클릭 시 팔로잉 페이지로 연결되는 기능 추가
  src/App.js
  src/components/common/Profile/OtherProfile.jsx
  src/components/common/Profile/UserProfile.jsx
Labels: feat

#145 [✨feat] 게시물 작성 기능 추가 #118
  package-lock.json
  package.json
  src/api/testAPI.js
  src/components/common/HeaderTest/Header.module.css
  src/components/layout/Layout.jsx
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: feat

#150 [feat] 헤더 검색 버튼 클릭 시, 검색 페이지로 이동하는 코드 추가 #149
  src/components/common/HeaderTest/Header.jsx
  src/components/common/HeaderTest/Header.module.css
  src/components/common/Input/Input.module.css
  src/components/layout/Layout.module.css
Labels: feat, style

#151 [fix] 로그인페이지 유효성 검토 후 바로 버튼 활성화 수정 및 css 간격 조정 #111
  src/pages/Join/JoinEmail/JoinEmail.jsx
  src/pages/Join/JoinEmail/JoinEmail.module.css
Labels: fix

#153 [style] product, search,login 코드 수정
  src/components/common/User/User.module.css
  src/components/common/User/UserSearch/UserSearch.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmail.module.css
  src/pages/Login/LoginMain/LoginMain.module.css
  src/pages/Product/AddProduct.jsx
  src/pages/Product/AddProduct.module.css
Labels: style

#154 [style] Product margin 값 변경
  src/pages/Product/AddProduct.module.css
Labels: style

#155 [fix] 회원가입 프로필 설정페이지 계정 Id 중복 검사 오류 수정 #111
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
  src/pages/Join/JoinProfileSetting/JoinProfileSettiong.module.css
Labels: fix

#156 [fix] 프로필 설정페이지 id 중복일때 오류사항임에도 활성화시키는 기능 오류 수정
  src/pages/Join/JoinProfileSetting/JoinProfileSetting.jsx
Labels: fix

#157 [🐛 fix] 프로필 수정페이지 오류메세지 안뜨는 오류 수정 #121
  src/pages/ProfileModification/ProfileModification.jsx
  src/pages/ProfileModification/ProfileModification.module.css
Labels: fix

#161 [🎨style]게시글 작성페이지 수정 #148
  src/App.js
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: style

#162 [style] Login font color 수정
  src/pages/Login/LoginEmail/LoginEmail.module.css
Labels: style

#163 [style] product 에러 color 변경
  src/pages/Product/AddProduct.module.css
Labels: style

#166 [fix] 게시글 일정 값에 말줄임 효과 추가하는 스타일 추가, 게시글 작성 일자 표현 방식 수정 #164
  src/components/common/Post/Post.jsx
  src/components/common/Post/Post.module.css
  src/components/layout/Layout.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
Labels: feat, design, fix

#168 [🎨style]게시글 작성페이지 수정 #148
  src/pages/Upload/Upload.jsx
  src/pages/Upload/Upload.module.css
Labels: style

#169 [fix] 프로필 페이지에서 게시글 앨범으로 보기 이미지 분리하는 로직 수정 #167
  src/components/common/Profile/ProfilePost.jsx
Labels: fix

#171 [feat] 게시글 업로드 시 전달되는 날짜 데이터 수정 #170
  src/pages/Upload/Upload.jsx
Labels: feat

#173 [fix] Confirm 모달 위치 수정 #172
  src/components/common/Modal/AlertModal.module.css
Labels: fix

#176 [fix] 배포를 위한 코드 수정 #175
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/common/HeaderTest/Header.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/Feed/FeedNone.jsx
Labels: fix

#177 [fix] 배포 환경에 맞춘 코드 수정
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/common/HeaderTest/Header.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/Feed/FeedNone.jsx
Labels: fix
